### ISSUE TITLE
Can't start on hypriot ios. 

### ISSUE THREAD

**Issue by thiloroehl** [acch/rpi-icinga#1]
Kindly provide a command line to start it. Using docker run - d - p 8080:80 rpi-icinga can't find the repo. Completely new to docker

**Comment by thiloroehl** [comment]
Found the manual under Readme.

**Comment by acch** [comment]
Good to hear that - have you been able to get the container running?

**Comment by thiloroehl** [comment]
$ docker -D run --rm --name icinga -p 80:80 -v $(pwd)/etc:/etc/icinga -v icinga_cache:/var/cache/icinga -v $(pwd)/log:/var/log acch/rpi-icinga
2019-03-31 21:23:42,689 CRIT Supervisor running as root (no user in config file)

Im not sure if its me because its the first time I try docker or if its Hypriot Ios. I cant see any process in the docker file and dont fand any logs.
Anything obvious im doing wrong ? I consider using a standard debian to cross check.

Thank you in advance

**Comment by thiloroehl** [comment]
Looking into the Docker File, I assume I first have to download this github repo :) It starts using this command but if there are copy commands im not sure if this should work.

**Comment by thiloroehl** [comment]
Downloaded the git. Manually logged in an started apache2 

root@f8e9af8191a8:/etc/apache2# service apache2 start
[FAIL] Starting Apache httpd web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
apache2: Syntax error on line 222 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf-enabled/icinga.conf: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.


Hm.... Lets call it a day :)

root@f8e9af8191a8:/etc/apache2# cd conf-enabled/
root@f8e9af8191a8:/etc/apache2/conf-enabled# ls
charset.conf  icinga.conf  localized-error-pages.conf  other-vhosts-access-log.conf  security.conf  serve-cgi-bin.conf
root@f8e9af8191a8:/etc/apache2/conf-enabled# tail /etc/apache2/conf-enabled/icinga.conf
tail: cannot open '/etc/apache2/conf-enabled/icinga.conf' for reading: No such file or directory
root@f8e9af8191a8:/etc/apache2/conf-enabled# ls -lrt
total 0
lrwxrwxrwx 1 root root 30 Mar 29 02:17 charset.conf -> ../conf-available/charset.conf
lrwxrwxrwx 1 root root 44 Mar 29 02:17 localized-error-pages.conf -> ../conf-available/localized-error-pages.conf
lrwxrwxrwx 1 root root 46 Mar 29 02:17 other-vhosts-access-log.conf -> ../conf-available/other-vhosts-access-log.conf
lrwxrwxrwx 1 root root 31 Mar 29 02:17 security.conf -> ../conf-available/security.conf
lrwxrwxrwx 1 root root 36 Mar 29 02:17 serve-cgi-bin.conf -> ../conf-available/serve-cgi-bin.conf
lrwxrwxrwx 1 root root 29 Mar 29 02:18 icinga.conf -> ../conf-available/icinga.conf
root@f8e9af8191a8:/etc/apache2/conf-enabled# cd ..
root@f8e9af8191a8:/etc/apache2# cd conf-available/
root@f8e9af8191a8:/etc/apache2/conf-available# ls
charset.conf  icinga.conf  localized-error-pages.conf  other-vhosts-access-log.conf  security.conf  serve-cgi-bin.conf
root@f8e9af8191a8:/etc/apache2/conf-available# ls -lrt
total 20
lrwxrwxrwx 1 root root   25 May  5  2017 icinga.conf -> ../../icinga/apache2.conf
-rw-r--r-- 1 root root  455 Nov  3 12:34 serve-cgi-bin.conf
-rw-r--r-- 1 root root 2174 Nov  3 12:34 security.conf
-rw-r--r-- 1 root root  189 Nov  3 12:34 other-vhosts-access-log.conf
-rw-r--r-- 1 root root 3224 Nov  3 12:34 localized-error-pages.conf
-rw-r--r-- 1 root root  315 Nov  3 12:34 charset.conf
root@f8e9af8191a8:/etc/apache2/conf-available# cd ..
root@f8e9af8191a8:/etc/apache2# cd ..
root@f8e9af8191a8:/etc# cd icinga/
root@f8e9af8191a8:/etc/icinga# ls
root@f8e9af8191a8:/etc/icinga#

**Comment by acch** [comment]
Let me try to answer your questions in order:

1. A `docker run ... acch/rpi-icinga` should automatically download (*pull*) the pre-built image and then *run* a container from it. Usually, that's exactly what you want to do - i.e. there's no need to download this Git repo. The Git repo, and especially the `Dockerfile` in it, is only required to *build* the image yourself.

2. The image simply exposes `/etc/icinga` as an external *volume*. This makes it easy to modify (and persist) your custom icinga configuration. However, this also means that you have to provide some configuration through the `/etc/icinga` volume - it can't be empty.

In order to start with the default configuration you will need to initialize the volume like so:

```
id=$(docker create acch/rpi-icinga)
docker cp $id:/etc/icinga etc
docker rm -v $id
```

This will create a temporary container from the image, copy the contents of `/etc/icinga`, and then delete the temporary container. You can then mount the newly created directory (`./etc/`) as a volume to the container like you already did above:

```
docker run ... -v $(pwd)/etc:/etc/icinga ...
```

*Please note*: This is non-obvious and I should have documented it. My fault - not yours. I'll add some instructions to the README as soon as I find the time.

3. Furthermore, the `/var/log` volume also needs some contents for the container to run properly. This shouldn't be the case. I've pushed a new image which should at least tolerate an empty `/var/log` volume.

So, in essence - would you mind:
- Generating the contents of the `etc/` directory like outlined above
- Giving it another try?

I hope this helps - please let me know if you have further questions.
Good luck!

**Comment by thiloroehl** [comment]
Hi, thanks a lot for your effort.

I added a 

$ docker cp $id:/var/log log

to create the needed log files and I can confirm it finally works :

 83 root      20   0    8100   3124   2732 R   0.3  0.3   0:00.06 top
    1 root      20   0   16508  13768   5968 S   0.0  1.4   0:01.18 supervisord
   10 nagios    20   0    8080   5312   4500 S   0.0  0.5   0:00.15 icinga
   12 root      20   0    7444   4288   3180 S   0.0  0.4   0:00.16 apache2
   13 www-data  20   0    7192   2984   1880 S   0.0  0.3   0:00.00 apache2
   14 www-data  20   0  229844   3444   2024 S   0.0  0.3   0:00.00 apache2
   15 www-data  20   0  229844   3444   2024 S   0.0  0.3   0:00.00 apache2
   75 root      20   0    3512    372    324 S   0.0  0.0   0:00.04 tail
   76 root      20   0    5196   3016   2644 S   0.0  0.3   0:00.04 bash



So... I would add to your doucmentation:

To start this docker file, first go to the home directory.

Create subdirectory with the current user for the etc config files and another one for the log files using : 

id=$(docker create acch/rpi-icinga)
docker cp $id:/etc/icinga etc
docker cp $id:/var/log log
docker rm -v $id

**Comment by acch** [comment]
Thanks - I'm glad that you managed to get it working.

I've added the following to README:
> Icinga configuration is stored in `/etc/icinga`, which is mounted as a volume to this image. When starting a container from this image for the first time it is necessary to initialize the volume with a default configuration. Run the following commands to copy the default configuration from a temporary container — the resulting `etc` directory can then be mounted to `/etc/icinga` as shown before

Initializing the `/var/log` volume should not be necessary with the latest image. You can get it with `docker pull acch/rpi-icinga`.

Let me know if this addresses the issue or if you're still having trouble.
All the best!

**Comment by thiloroehl** [comment]
Kindly consider to add "as a volume" from the local path $pwd - Its the first time I use this environment variable and it took long to understand the semantik from the mount command.

I pulled the image again - I didnt know this has to be done because I assume the update is done automatically and I can confirm the log topic is now solved.

Thanks a lot.

I can confirm icinga is starting, same as apache. Issue is closed.
